-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: database:3306
-- Generation Time: Jan 28, 2026 at 06:40 PM
-- Server version: 10.6.23-MariaDB-ubu2204
-- PHP Version: 8.3.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `article_id` int(11) NOT NULL,
  `FK_user_id` int(11) NOT NULL,
  `FK_category_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `is_active` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`article_id`, `FK_user_id`, `FK_category_id`, `title`, `content`, `created_at`, `updated_at`, `is_active`) VALUES
(1, 1, 1, 'How to Build a Website in 2026', 'Building a website in 2026 is more accessible, powerful, and flexible than ever before. Advances in tools, frameworks, and AI-driven platforms have made it possible for beginners and professionals alike to create modern, high-performing websites without starting from scratch. Whether you are launching a personal blog, an online store, or a business website, the process follows a few essential steps.\r\n\r\nThe first step is defining the purpose of your website. Understanding your audience and goals helps shape design choices, content structure, and functionality. In 2026, user experience is a top priority, so websites must be fast, mobile-friendly, and easy to navigate. Planning your layout and content before building saves time and leads to better results.\r\n\r\nNext comes choosing the right tools and technologies. Many creators now use website builders and content management systems that integrate AI features, such as automatic layout suggestions, content generation, and accessibility checks. For developers, modern frameworks like React-based systems and lightweight backend services allow for faster development and improved performance. Cloud hosting platforms provide scalability, security, and reliable uptime with minimal setup.\r\n\r\nDesign and content creation are equally important. Clean layouts, readable typography, and consistent branding help establish trust. In 2026, accessibility is no longer optional—websites must be usable for people with different abilities and devices. High-quality content, optimized for both users and search engines, ensures your site is discoverable and engaging.\r\n\r\nFinally, testing and maintenance keep a website successful over time. Regular updates, performance monitoring, and security checks protect your site and improve user experience. With the right approach and modern tools, building a website in 2026 is not only achievable but also an opportunity to create something truly impactful in the digital world.', '2026-01-08 10:43:37', '2026-01-08 20:17:08', 1),
(2, 2, 3, 'Top 10 Places to Visit in Europe', 'Europe is one of the most diverse and culturally rich continents in the world, offering travelers an extraordinary range of experiences within relatively short distances. From historic cities shaped by ancient civilizations to breathtaking coastal and mountain landscapes, Europe combines tradition and modern life in a way few places can. Whether visitors are drawn by art, architecture, food, or natural beauty, the continent has something for everyone.\r\n\r\nCities such as Paris, Rome, and London stand at the heart of European history and culture. Paris is celebrated for its romantic atmosphere, world-famous museums, and elegant streets, while Rome offers a direct connection to the ancient world through its ruins, churches, and timeless architecture. London, a global metropolis, blends royal heritage with contemporary culture, offering iconic landmarks alongside vibrant neighborhoods and multicultural influences.\r\n\r\nSouthern Europe attracts visitors with its warmth, color, and relaxed lifestyle. Barcelona impresses with its unique architecture and Mediterranean energy, combining beaches with bold artistic expression. In Greece, destinations like Santorini showcase dramatic landscapes and traditional villages, where white buildings contrast beautifully with deep blue seas. These places invite travelers to slow down, enjoy local cuisine, and experience centuries-old traditions.\r\n\r\nCentral and Northern Europe provide equally memorable experiences. Cities like Prague and Vienna captivate visitors with their classical beauty, historic squares, and musical heritage. Amsterdam’s canals and museums reflect a strong connection to art and innovation, while Berlin stands out for its powerful modern history and creative spirit. For those seeking natural beauty, Switzerland’s alpine regions offer stunning views, outdoor adventures, and peaceful lakeside towns.\r\n\r\nTogether, these destinations represent the best of Europe’s cultural depth, historical significance, and natural diversity. Exploring them allows travelers to experience different languages, lifestyles, and traditions, all within one remarkable continent.', '2026-01-08 10:43:37', '2026-01-09 19:27:08', 1),
(3, 1, 4, 'test', 'dfdsfdfdfs', '2026-01-08 10:54:21', '2026-01-08 13:23:22', 0),
(4, 1, 3, 'How to Get Dogs to the Moon Safely', 'Following the incredible success of the 1957 Laika mission, ESA now wants to shoot a dog to the moon for fun.\r\n\r\nAfter the 1957 Laika flight proved space travel possible, renewed interest in animal spaceflight resurfaces. A satirical proposal suggests sending a dog to the Moon, but modern science would demand safety, ethics, and purpose. Any mission would require rigorous training, life support, radiation shielding, and a humane return plan. International agencies would face scrutiny from veterinarians, ethicists, and the public. Today, robots outperform animals for exploration, making such ideas symbolic rather than practical. Remembering Laika reminds us progress carries responsibility: curiosity must never outweigh compassion, and exploration should advance knowledge without unnecessary suffering, while respecting history, science, and moral values.', '2026-01-08 12:57:28', '2026-01-08 20:17:52', 1),
(5, 1, 5, 'How Jazz Music Can Help Vegetables Grow', 'Jazz music may do more than soothe human souls—it might also help vegetables grow. Research into sound vibrations and plant biology suggests that plants can respond to their environment in subtle but measurable ways. While vegetables do not hear music as humans do, they are sensitive to vibrations, airflow, and rhythmic stimuli. Jazz, with its smooth tempos, rich harmonies, and low-frequency bass lines, creates a sound environment that may positively influence plant development.\r\n\r\nGentle vibrations from music can stimulate plant cells, potentially improving nutrient uptake and encouraging stronger root and stem growth. Jazz is especially well suited for this because it avoids the harsh, repetitive patterns found in louder or more aggressive genres. Its natural variation and improvisation mirror patterns found in nature, such as wind movement or flowing water, which plants have adapted to over millions of years.\r\n\r\nSome gardeners and small-scale farmers report healthier leaves, thicker stalks, and improved overall vitality when jazz music is played regularly near crops. The calming effect of jazz may also benefit the people tending the plants, encouraging more attentive care, consistent watering, and a relaxed gardening environment—all of which contribute indirectly to better growth.\r\n\r\nAlthough more controlled scientific studies are needed, the idea of jazz-enhanced agriculture highlights the complex relationship between living organisms and their surroundings. Whether through vibration, rhythm, or human interaction, jazz appears to bring harmony not only to listeners, but potentially to gardens as well. In the end, a softly swinging trumpet might help vegetables grow just a little greener.', '2026-01-08 13:16:19', '2026-01-08 21:04:08', 1),
(6, 1, 1, 'Students Design Brand New Website', 'When students design a website, they gain far more than technical skills. The process combines creativity, problem-solving, and teamwork, making it a powerful learning experience. From planning layouts to choosing colors, fonts, and images, students learn how design choices affect usability and communication. They must think about their audience and purpose, which strengthens critical thinking and digital literacy.\r\n\r\nWebsite design also introduces practical technical skills such as HTML, CSS, content management systems, and basic accessibility principles. Students learn how to structure information clearly, ensure pages load efficiently, and adapt designs for different devices. Testing and debugging teach patience and attention to detail.\r\n\r\nCollaboration plays a key role, as students often work in teams to divide tasks like content writing, coding, and visual design. This mirrors real-world projects and builds communication skills. Overall, designing a website empowers students to create something tangible, boosting confidence while preparing them for future academic and professional challenges in an increasingly digital world.', '2026-01-08 13:22:45', '2026-01-08 15:41:08', 1),
(7, 1, 4, 'The Importance of Good Sleep for Overall Health', 'Sleep is one of the most essential yet often overlooked aspects of good health. In a fast-paced world filled with screens, deadlines, and constant stimulation, many people sacrifice sleep without realizing the long-term consequences. Quality sleep is not a luxury; it is a biological necessity that supports both physical and mental well-being.\r\n\r\nDuring sleep, the body carries out vital processes such as tissue repair, muscle growth, and immune system strengthening. The brain also uses this time to process information, consolidate memories, and regulate emotions. When sleep is consistently insufficient, these processes are disrupted, increasing the risk of health problems such as heart disease, weakened immunity, obesity, and diabetes.\r\n\r\nSleep also plays a major role in mental health. Poor sleep can contribute to stress, anxiety, depression, and difficulty concentrating. Even short-term sleep deprivation can affect mood, reaction time, and decision-making. Over time, chronic sleep loss may impair cognitive function and reduce overall quality of life.\r\n\r\nEstablishing healthy sleep habits can make a significant difference. Maintaining a regular sleep schedule, reducing screen use before bedtime, and creating a calm sleeping environment help improve sleep quality. By prioritizing rest, individuals support their bodies and minds, leading to better energy, focus, and long-term health.', '2026-01-08 21:05:27', '2026-01-09 11:17:59', 1),
(8, 3, 5, 'Why Simple Home Cooking Is Making a Comeback', 'Why Simple Home Cooking Is Making a Comeback\r\n\r\nIn a world of food delivery apps, viral recipes, and AI-generated meal plans, something unexpected is happening in 2026: people are falling back in love with simple home cooking. Not because it’s trendy—but because it feels good.\r\n\r\nThe Comfort Factor\r\n\r\nCooking at home has become less about perfection and more about comfort. A pot of pasta, a homemade soup, or a pan of roasted vegetables offers something takeout never can: a sense of control and calm. After long days filled with screens and notifications, chopping an onion or stirring a sauce feels grounding.\r\nPeople aren’t chasing complicated techniques anymore. They want food that tastes familiar, nourishing, and real.\r\n\r\nFewer Ingredients, Better Flavor\r\n\r\nOne of the biggest shifts in home cooking is the move toward short ingredient lists. Instead of recipes that call for 20 items, modern home cooks are focusing on quality over quantity.\r\n\r\nThink:\r\nFresh tomatoes instead of canned sauces\r\nGood olive oil instead of heavy seasoning blends\r\nSeasonal vegetables prepared simply\r\nThe result? Meals that taste cleaner, brighter, and more satisfying.\r\nCooking as Self-Care\r\n\r\nFood has officially crossed into the self-care space. Cooking a meal for yourself is now seen as an act of kindness, not a chore. It’s a way to slow down, step away from endless scrolling, and reconnect with your body.\r\nEven quick meals count. A ten-minute breakfast or a basic dinner still creates a pause in the day—and that pause matters.\r\n\r\nSharing Food, Even Digitally\r\n\r\nWhile many people cook at home, food is still deeply social. Photos of imperfect meals are replacing polished restaurant shots. Blogs and social feeds are filled with real kitchens, real messes, and honest reviews of what worked—and what didn’t. Food content feels human again.\r\n\r\nFinal Thoughts\r\n\r\nSimple home cooking isn’t about going backward. It’s about choosing balance. In 2026, food is less about impressing others and more about taking care of ourselves.\r\nAnd sometimes, the best meal is the one you made with whatever was already in your fridge.', '2026-01-09 15:16:46', '2026-01-09 15:17:57', 1),
(9, 3, 5, 'Grandma’s Recipes: Why Old-Fashioned Cooking Still Wins', 'Every family has at least one recipe that doesn’t exist on paper. No measurements. No timers. Just memory, instinct, and a phrase like, “You’ll know when it’s ready.” These are grandma’s recipes—and somehow, they always taste better than anything made from a modern cookbook.\r\n\r\nCooking Without Rules\r\nGrandma never needed a smartphone or a recipe app. She cooked by feel. A pinch of salt, a splash of milk, a quick taste from the spoon. Mistakes were rare, but when they happened, they became part of the tradition.\r\nThis kind of cooking teaches something important: food doesn’t have to be perfect to be good. It just has to be made with care.\r\n\r\nMore Than Just Food\r\nGrandma’s recipes were never just about eating. They were about:\r\nFeeding the whole family without waste\r\nTurning simple ingredients into something special\r\nBringing everyone to the table, no matter how busy life was\r\nA pot of soup meant warmth. Fresh bread meant comfort. Dessert meant celebration—even on ordinary days.\r\n\r\nWhy These Recipes Are Returning\r\nIn 2026, people are rediscovering old family recipes for a reason. They’re tired of overly processed food and complicated instructions. Grandma’s cooking feels honest. It uses basic ingredients and techniques that have survived generations for a reason—they work.\r\nThese recipes are also flexible. They adapt to what you have in the kitchen, which makes them perfect for modern, practical cooking.\r\n\r\nPreserving the Stories\r\nOne of the biggest losses is when these recipes disappear. That’s why more people are writing them down, sharing them online, and passing them on. When you cook one of grandma’s dishes, you’re not just making food—you’re keeping a story alive.\r\nEvery scratch on the old recipe card, every unclear instruction, is part of its charm.\r\n\r\nGrandma’s recipes remind us that food doesn’t need to be trendy or expensive to be meaningful. It just needs heart. In a fast-moving world, these slow, familiar dishes give us something steady to hold onto.\r\nAnd no matter how many new recipes come along, grandma’s will always taste like home.', '2026-01-09 15:23:05', '2026-01-09 15:23:05', 1),
(10, 3, 5, 'Where the Islands Meet: The Rise of Hawaiian–Cuban Fusion Cuisine', 'Two island cultures, thousands of miles apart, are coming together in an unexpected and exciting way. Hawaiian–Cuban fusion cuisine is emerging as one of the most creative food movements of the moment, blending the laid-back freshness of Hawaii with the bold, soulful flavors of Cuba.\r\n\r\nThe result is food that feels vibrant, colorful, and deeply rooted in tradition—yet completely new.\r\n\r\nWhat Makes Hawaiian and Cuban Cuisine a Perfect Match\r\n\r\nAt first glance, these cuisines may seem different, but they share important foundations:\r\n- A love for slow-cooked meats\r\n- Heavy use of citrus, garlic, and herbs\r\n- A strong connection to island life and fresh ingredients\r\n\r\nFood that’s meant to be shared\r\nHawaiian cooking brings brightness and balance, while Cuban food adds depth, warmth, and spice.\r\n\r\nHawaiian Elements in the Fusion\r\n\r\nFrom Hawaii, this fusion borrows:\r\n- Fresh seafood like tuna, mahi-mahi, and shrimp\r\n- Tropical fruits such as pineapple, mango, and guava\r\n- Light marinades using soy sauce, ginger, and sesame\r\n- Rice-based dishes that keep meals grounded and comforting\r\nThese ingredients keep the dishes fresh and vibrant, often served raw or lightly cooked to preserve natural flavors.\r\n\r\nCuban Flavors That Anchor the Dishes\r\nCuban cuisine adds richness and soul through:\r\n- Mojo sauce made with garlic, citrus, and olive oil\r\n- Slow-roasted pork seasoned with cumin and oregano\r\n- Black beans and rice as hearty foundations\r\n- Plantains, both sweet and savory\r\nThese elements bring warmth and depth, transforming light island ingredients into satisfying, layered meals.\r\n\r\nSignature Fusion Dishes to Watch\r\nSome standout Hawaiian–Cuban fusion creations include:\r\n- Mojo-marinated pork with pineapple rice\r\n- Ahi tuna poke with citrus-garlic mojo drizzle\r\n- Plantain tostones topped with spicy tuna and avocado\r\n- Lechón-style pulled pork sliders on sweet Hawaiian rolls\r\n- Guava-glazed mahi-mahi with black bean coconut rice\r\n\r\nEach dish balances freshness with richness, sweetness with acidity, and tradition with innovation.\r\n\r\nWhy This Fusion Feels Right Now\r\nHawaiian–Cuban fusion reflects what modern diners want: bold flavors without heaviness, cultural respect without rigidity, and meals that feel both comforting and adventurous. It’s casual enough for beachside dining but complex enough for modern kitchens. Most importantly, it celebrates two cultures that understand food as a way of bringing people together.\r\n\r\nHawaiian–Cuban fusion cuisine isn’t about replacing tradition—it’s about letting two island histories speak to each other. The flavors are bright, soulful, and full of movement, just like the cultures behind them. This is island food reimagined—and it’s only just getting started.', '2026-01-09 15:28:41', '2026-01-09 15:28:41', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`article_id`),
  ADD KEY `FK_user_id` (`FK_user_id`),
  ADD KEY `FK_category_id` (`FK_category_id`);
ALTER TABLE `articles` ADD FULLTEXT KEY `ft_title_content` (`title`,`content`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `article_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `articles`
--
ALTER TABLE `articles`
  ADD CONSTRAINT `articles_ibfk_1` FOREIGN KEY (`FK_user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `articles_ibfk_2` FOREIGN KEY (`FK_category_id`) REFERENCES `categories` (`category_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
